# Select image from https://hub.docker.com/r/_/php/
image: php:7.1

services:
  - mysql:5.6

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: intranetv3
  MYSQL_ROOT_PASSWORD: root
  DATABASE_URL: mysql://root:root@mysql:3306/intranetv3

before_script:
  - bash ci/docker_install.sh > /dev/null
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php bin/console doctrine:database:create


test:app:
  script:
  - phpunit --configuration phpunit.xml